# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

q1 = Question.create(title: "How many chickens crossed the road to get to the other side on a sunday?",description:"Hashtag Etsy Thundercats Odd Future meh keytar, heirloom DIY forage slow-carb gentrify messenger bag. Pork belly Odd Future art party, artisan Vice semiotics Bushwick taxidermy cronut small batch Brooklyn pug shabby chic. PBR Odd Future post-ironic Kickstarter, narwhal Echo Park beard crucifix stumptown cred meggings lumbersexual fingerstache. Austin asymmetrical Tumblr PBR&B. Blog McSweeney's Truffaut put a bird on it. Jean shorts heirloom Thundercats, Blue Bottle put a bird on it mumblecore ugh YOLO PBR sriracha asymmetrical. Meditation vegan Intelligentsia Thundercats." )
q2 = Question.create(title: "Why do people eat food that doesn't taste good sometimes just becuase it is healthy?",description: "Crucifix Pitchfork cold-pressed, Brooklyn you probably haven't heard of them whatever tote bag umami. Cliche Vice retro kogi meh, bitters bicycle rights fanny pack Etsy four dollar toast paleo drinking vinegar Odd Future. Before they sold out chia readymade, flannel Etsy sartorial viral distillery craft beer paleo Carles. Wayfarers deep v kogi, PBR&B letterpress craft beer DIY narwhal Pinterest fashion axe single-origin coffee. Trust fund messenger bag health goth craft beer ethical, migas Shoreditch. Vice vegan brunch, plaid messenger bag blog gastropub iPhone freegan pork belly photo booth. Pop-up selfies food truck ugh DIY art party, cardigan Williamsburg sriracha kale chips iPhone.")
q3 = Question.create(title: "Can the world fall flat on its face if the world is rounder than the earth?",description: "Irony vinyl Odd Future vegan artisan, Williamsburg asymmetrical fingerstache street art. Occupy artisan heirloom Helvetica, readymade kogi Brooklyn blog cardigan fixie mlkshk beard. Messenger bag Blue Bottle 8-bit, narwhal before they sold out Williamsburg lo-fi Etsy Brooklyn occupy. American Apparel farm-to-table PBR&B Bushwick. Slow-carb literally blog, yr readymade +1 ugh plaid aesthetic mixtape tilde selfies typewriter cold-pressed locavore. Shoreditch butcher direct trade, Helvetica sustainable distillery McSweeney's +1 gentrify mixtape chillwave. Kogi fashion axe meditation gentrify, skateboard yr viral four dollar toast salvia Echo Park wolf craft beer Bushwick small batch.")

Response.create(question_id: 1, description: 'Duo omnis libris expetenda cu. Possim numquam forensibus mel an. Usu id aeterno fastidii explicari. Illud summo sit et, dicta similique an quo. Minimum constituto reformidans no ius. Eu nihil adipisci senserit vim. Et tritani scaevola eam.')
Response.create(question_id: 2, description: 'Cum te amet dicat ancillae. Tation nostrum at est. Vis nisl unum pertinacia ad, virtute inimicus contentiones mea ei. Ne rebum inani patrioque nam, case meis mea ei. Ius eu modus epicuri apeirian, aeterno definitionem at his. Solum constituto sed ea, animal dolores per ut. Modus quodsi copiosae duo eu, nam ea vero idque movet.')
Response.create(question_id: 3, description: 'Mea odio ferri iisque eu, atomorum sadipscing vim at. In sed brute epicurei temporibus. Sed ea latine splendide. Labores repudiandae et vel, an vel quas voluptaria, erant expetendis est ut. Ius option legendos in, ut est idque utamur aperiam, ius cu euismod offendit suavitate. Pro cu ullum patrioque.')
